-- GEN_CLASE
-- + ID_CLASE
-- + FID_GCU_CURSO
-- + CODIGO
-- + ...
-- 
-- GEN_DOCENTE
-- + NOMBRE
--
-- GEN_CLASE_DOCENTE
-- + ...
--
-- 
-- EPO_PETICION:
-- = FID_GEN_CLASE hacerla FK 
-- + FID_RUBRICA(FK) bigint NOT NULL (af. FID_TIPO_ARCHIVO)
-- + DESCRIPCION text NULL (af. NOMBRE)
-- + GRUPAL bit NOT NULL (af. REFERENCIA)
-- 
-- 
-- exec sp_MSforeachtable 'select count(*) as nr_of_rows, ''?'' as table_name from ?'


-- EPO_PERIODO_ACADEMICO
DELETE FROM EPO_PETICION;
DELETE FROM GEN_CLASE;
DELETE FROM EPO_PERIODO_ACADEMICO;
DBCC CHECKIDENT (EPO_PERIODO_ACADEMICO, RESEED, 0);
INSERT INTO EPO_PERIODO_ACADEMICO VALUES ('2008-0', '2009-05-01', '2009-05-30');
INSERT INTO EPO_PERIODO_ACADEMICO VALUES ('2008-1', '2009-05-01', '2009-05-30');
INSERT INTO EPO_PERIODO_ACADEMICO VALUES ('2008-2', '2009-05-01', '2009-05-30');
INSERT INTO EPO_PERIODO_ACADEMICO VALUES ('2009-0', '2009-05-01', '2009-05-30');
INSERT INTO EPO_PERIODO_ACADEMICO VALUES ('2009-1', '2009-05-01', '2009-05-30');

-- GCU_CURSO
DELETE FROM GCU_CURSO;
DBCC CHECKIDENT (GCU_CURSO, RESEED, 0);
INSERT INTO GCU_CURSO VALUES ('Diseño de Software','DISESW',3,3,3,3,NULL,NULL,NULL);
INSERT INTO GCU_CURSO VALUES ('Inteligencia Artificial','INTART',3,3,3,3,NULL,NULL,NULL);
INSERT INTO GCU_CURSO VALUES ('Admin. de Proyectos de Software','APSOFT',3,3,3,3,NULL,NULL,NULL);
INSERT INTO GCU_CURSO VALUES ('Ing. Web','INGWEB',3,3,3,3,NULL,NULL,NULL);
INSERT INTO GCU_CURSO VALUES ('Métodos Numéricos','METNUM',3,3,3,3,NULL,NULL,NULL);
INSERT INTO GCU_CURSO VALUES ('Electrónica','ELECTO',3,3,3,3,NULL,NULL,NULL);



-- GEN
DELETE FROM GEN_CLASE;
DBCC CHECKIDENT (GEN_CLASE, RESEED, 0);
INSERT INTO GEN_CLASE VALUES (5,1,'horario','7875');
INSERT INTO GEN_CLASE VALUES (5,1,'horario','7876');
INSERT INTO GEN_CLASE VALUES (5,2,'horario','8012');
INSERT INTO GEN_CLASE VALUES (5,2,'horario','8013');
INSERT INTO GEN_CLASE VALUES (5,3,'horario','8752');
INSERT INTO GEN_CLASE VALUES (5,3,'horario','8783');
INSERT INTO GEN_CLASE VALUES (5,3,'horario','8784');
INSERT INTO GEN_CLASE VALUES (5,3,'horario','8785');
INSERT INTO GEN_CLASE VALUES (5,4,'horario','9141');
INSERT INTO GEN_CLASE VALUES (5,4,'horario','9142');
INSERT INTO GEN_CLASE VALUES (5,5,'horario','2222');
INSERT INTO GEN_CLASE VALUES (5,6,'horario','7777');



-- EPO_TIPO_ARCHIVO
DELETE FROM EPO_TIPO_ARCHIVO;
DBCC CHECKIDENT (EPO_TIPO_ARCHIVO, RESEED, 0);
INSERT INTO EPO_TIPO_ARCHIVO (EXTENSION,NOMBRE,ICONO) VALUES ('pdf','Portable Document Format (PDF)','archivo.jpg');
INSERT INTO EPO_TIPO_ARCHIVO (EXTENSION,NOMBRE,ICONO) VALUES ('docx','Documento de Texto','archivo.jpg');
INSERT INTO EPO_TIPO_ARCHIVO (EXTENSION,NOMBRE,ICONO) VALUES ('xlsx','Hoja de Cálculo','archivo.jpg');
INSERT INTO EPO_TIPO_ARCHIVO (EXTENSION,NOMBRE,ICONO) VALUES ('pptx','Presentación de Diapositivas','archivo.jpg');
INSERT INTO EPO_TIPO_ARCHIVO (EXTENSION,NOMBRE,ICONO) VALUES ('','Proyecto de NetBeans','archivo.jpg');
INSERT INTO EPO_TIPO_ARCHIVO (EXTENSION,NOMBRE,ICONO) VALUES ('','Proyecto de VisualStudio','archivo.jpg');
INSERT INTO EPO_TIPO_ARCHIVO (EXTENSION,NOMBRE,ICONO) VALUES ('lvproj','Proyecto de LabView','archivo.jpg');
INSERT INTO EPO_TIPO_ARCHIVO (EXTENSION,NOMBRE,ICONO) VALUES ('mat','Script de MatLab','archivo.jpg');


-- EPO_RUBRICA
DELETE FROM EPO_RUBRICA;
DBCC CHECKIDENT (EPO_RUBRICA, RESEED, 0);
INSERT INTO EPO_RUBRICA (CODIGO,NOMBRE) VALUES ('ALGOR','Eval. de Algoritmos');
INSERT INTO EPO_RUBRICA (CODIGO,NOMBRE) VALUES ('PAPER','Eval. de Papers');
INSERT INTO EPO_RUBRICA (CODIGO,NOMBRE) VALUES ('DISSW','Eval. de Diseño de Software');
INSERT INTO EPO_RUBRICA (CODIGO,NOMBRE) VALUES ('DISBD','Eval. de Diseño de Base de datos');
INSERT INTO EPO_RUBRICA (CODIGO,NOMBRE) VALUES ('PRUSW','Eval. de Pruebas de Software');


-- EPO_PETICION
DELETE FROM EPO_PETICION;
DBCC CHECKIDENT (EPO_PETICION, RESEED, 0);
INSERT INTO EPO_PETICION VALUES (1, NULL, 1, 1, '2009-05-01', '2009-05-30', NULL, 'False', 'False', 'Estandar GUI','desc... de Estandar GUI');
INSERT INTO EPO_PETICION VALUES (1, NULL, 2, 2, '2009-05-01', '2009-05-30', NULL, 'False', 'False', 'Plan de Pruebas','desc... de Plan de Pruebas');
INSERT INTO EPO_PETICION VALUES (1, NULL, 3, 3, '2009-05-01', '2009-05-30', NULL, 'False', 'False', 'Especificacion de UC','desc... de Especificacion de UC');
INSERT INTO EPO_PETICION VALUES (1, NULL, 4, 4, '2009-05-01', '2009-05-30', NULL, 'False', 'False', 'Contrato de Servicios','desc... de Contrato de Servicios');
INSERT INTO EPO_PETICION VALUES (1, NULL, 5, 5, '2009-05-01', '2009-05-30', NULL, 'False', 'False', 'Procedimiento de Prueba','desc... de Procedimiento de Prueba');



-- EPO_ESQUEMA_GRUPO
DELETE FROM EPO_ESQUEMA_GRUPO;
DBCC CHECKIDENT (EPO_ESQUEMA_GRUPO, RESEED, 0);
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (1,'T1 y T2');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (1,'T4 y T5');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (1,'Trabajo Final');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (2,'T1 y T3');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (2,'T4 y E.F.');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (2,'Trabajo de Medio Ciclo');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (3,'T1');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (3,'T5');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (3,'Trabajo Final');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (4,'T1');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (4,'T2');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (4,'T3');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (4,'T4');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (4,'T5');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (5,'Trabajo Final');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (6,'T4 y T5');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (6,'Trabajo Final');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (7,'T1 y T2');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (7,'Trabajo Final');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (8,'Proyecto Final');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (8,'T4 y T5');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (8,'Trabajo Final');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (9,'T1 y T2');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (9,'T4 y T5');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (9,'Trabajo Final');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (10,'UNICO');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (11,'T1 y T2');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (11,'Trabajo Final');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (12,'T1 y T2');
INSERT INTO EPO_ESQUEMA_GRUPO VALUES (12,'T4 y T5');







select * from EPO_RUBRICA;
select * from EPO_CRITERIO_EVALUACION;

SELECT
PAC_RESULTADO_PROGRAMA.NOMBRE as RP,
PAC_CAPACIDAD_MEDIBLE.NOMBRE as CM,
PAC_CRITERIO.NOMBRE as CRITERIO
-- ,PAC_NIVEL.NOMBRE AS NIVEL
FROM
PAC_RESULTADO_PROGRAMA
JOIN PAC_CAPACIDAD_MEDIBLE ON PAC_RESULTADO_PROGRAMA.ID_RESULTADO_PROGRAMA = PAC_CAPACIDAD_MEDIBLE.FID_RESULTADO_PROGRAMA
JOIN PAC_CRITERIO ON PAC_CRITERIO.FID_CAPACIDAD_MEDIBLE = PAC_CAPACIDAD_MEDIBLE.ID_CAPACIDAD_MEDIBLE
-- JOIN PAC_NIVEL ON PAC_NIVEL.FID_CRITERIO = PAC_CRITERIO.ID_CRITERIO